networks:
  looper-net:
    driver: bridge

services:
  http-server-projeto-looper:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: http-server-projeto-looper
    networks:
      - looper-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d/
    networks:
      - looper-net
    depends_on:
      - http-server-projeto-looper

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - looper-net
    depends_on:
      - http-server-projeto-looper

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - looper-net
    depends_on:
      - prometheus
