server {
    # Escuta na porta 80 do container
    listen 80;
    server_name localhost;

    # Encaminha as requisições da raiz para o serviço Go
    location / {
        # O NGINX resolve o nome do container "http-server-projeto-korp" automaticamente na rede bridge
        proxy_pass http://http-server-projeto-korp:8080;
        
        # Repassa os cabeçalhos originais da requisição (Boas práticas)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
